/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\lzw\\Study\\xianniu-docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-716ce9de",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-716ce9de").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-0ead3faa",
    path: "/comps/date.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-0ead3faa").then(next)
    },
  },
  {
    name: "v-6ba45814",
    path: "/comps/search.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-6ba45814").then(next)
    },
  },
  {
    name: "v-2b7e91e1",
    path: "/comps/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b7e91e1").then(next)
    },
  },
  {
    path: "/comps/index.html",
    redirect: "/comps/"
  },
  {
    name: "v-1e6715ae",
    path: "/cli/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e6715ae").then(next)
    },
  },
  {
    path: "/cli/index.html",
    redirect: "/cli/"
  },
  {
    name: "v-08cb68e1",
    path: "/log/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-08cb68e1").then(next)
    },
  },
  {
    path: "/log/index.html",
    redirect: "/log/"
  },
  {
    name: "v-78c51817",
    path: "/theme/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-78c51817").then(next)
    },
  },
  {
    path: "/theme/index.html",
    redirect: "/theme/"
  },
  {
    name: "v-b145cd60",
    path: "/comps/table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b145cd60").then(next)
    },
  },
  {
    name: "v-b9b52694",
    path: "/comps/dialog.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b9b52694").then(next)
    },
  },
  {
    name: "v-60054f1a",
    path: "/tools/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-60054f1a").then(next)
    },
  },
  {
    path: "/tools/index.html",
    redirect: "/tools/"
  },
  {
    name: "v-398733cb",
    path: "/request/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-398733cb").then(next)
    },
  },
  {
    path: "/request/index.html",
    redirect: "/request/"
  },
  {
    name: "v-55967dd0",
    path: "/tools/tools.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-55967dd0").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]