/**
 * Generated by "@vuepress/internal-routes"
 */

import { injectComponentOption, ensureAsyncComponentsLoaded } from '@app/util'
import rootMixins from '@internal/root-mixins'
import GlobalLayout from "C:\\lzw\\Study\\xianniu-docs\\node_modules\\@vuepress\\core\\lib\\client\\components\\GlobalLayout.vue"

injectComponentOption(GlobalLayout, 'mixins', rootMixins)
export const routes = [
  {
    name: "v-716ce9de",
    path: "/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-716ce9de").then(next)
    },
  },
  {
    path: "/index.html",
    redirect: "/"
  },
  {
    name: "v-1e6715ae",
    path: "/cli/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-1e6715ae").then(next)
    },
  },
  {
    path: "/cli/index.html",
    redirect: "/cli/"
  },
  {
    name: "v-2b7e91e1",
    path: "/comps/",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-2b7e91e1").then(next)
    },
  },
  {
    path: "/comps/index.html",
    redirect: "/comps/"
  },
  {
    name: "v-b145cd60",
    path: "/comps/table.html",
    component: GlobalLayout,
    beforeEnter: (to, from, next) => {
      ensureAsyncComponentsLoaded("Layout", "v-b145cd60").then(next)
    },
  },
  {
    path: '*',
    component: GlobalLayout
  }
]