/**
 * Generated by "@vuepress/internal-site-data"
 */
export const siteData = {
  "title": "贤牛",
  "description": "贤牛后台管理文档",
  "base": "/xianniu-docs/",
  "headTags": [
    [
      "link",
      {
        "rel": "shortcut icon",
        "type": "image/x-icon",
        "href": "/xianniu-docs/jyjwebdocs/favicon.ico"
      }
    ]
  ],
  "pages": [
    {
      "title": "介绍",
      "frontmatter": {},
      "regularPath": "/",
      "relativePath": "README.md",
      "key": "v-716ce9de",
      "path": "/"
    },
    {
      "title": "xn-date",
      "frontmatter": {},
      "regularPath": "/comps/date.html",
      "relativePath": "comps/date.md",
      "key": "v-0ead3faa",
      "path": "/comps/date.html"
    },
    {
      "title": "组件",
      "frontmatter": {},
      "regularPath": "/comps/",
      "relativePath": "comps/README.md",
      "key": "v-2b7e91e1",
      "path": "/comps/"
    },
    {
      "title": "xn-dialog",
      "frontmatter": {},
      "regularPath": "/comps/dialog.html",
      "relativePath": "comps/dialog.md",
      "key": "v-b9b52694",
      "path": "/comps/dialog.html"
    },
    {
      "title": "后台管理脚手架",
      "frontmatter": {},
      "regularPath": "/cli/",
      "relativePath": "cli/README.md",
      "key": "v-1e6715ae",
      "path": "/cli/"
    },
    {
      "title": "xn-table",
      "frontmatter": {},
      "regularPath": "/comps/table.html",
      "relativePath": "comps/table.md",
      "key": "v-b145cd60",
      "path": "/comps/table.html"
    },
    {
      "title": "xn-search",
      "frontmatter": {},
      "regularPath": "/comps/search.html",
      "relativePath": "comps/search.md",
      "key": "v-6ba45814",
      "path": "/comps/search.html"
    }
  ],
  "themeConfig": {
    "sidebarDepth": 2,
    "sidebar": [
      {
        "title": "介绍",
        "path": "/"
      },
      {
        "title": "脚手架",
        "path": "/cli/"
      },
      {
        "title": "组件",
        "path": "/comps/",
        "collapsable": false,
        "sidebarDepth": 1,
        "children": [
          {
            "title": "xn-table",
            "path": "/comps/table"
          },
          {
            "title": "xn-date",
            "path": "/comps/date"
          },
          {
            "title": "xn-search",
            "path": "/comps/search"
          },
          {
            "title": "xn-dialog",
            "path": "/comps/dialog"
          }
        ]
      }
    ]
  }
}